### ISSUE TITLE
Request: clarify usage of docker-socket-proxy network best practices

### ISSUE THREAD

**Issue by charles-lehman** [linuxserver/docker-documentation#224]
I'm switching over to SWAG from Caddy and am trying to be extra sure I set up the Docker socket proxy container correctly. 

### Question
The current docs are written in a slightly ambiguous way that deserves to be clarified given the gravity of the potential error. I've pasted the current text from the [docker-socket-proxy readme ](https://github.com/linuxserver/docker-socket-proxy?tab=readme-ov-file#application-setup)below; emphasis in bold is mine.

> The container should be **run on the same docker network** as the service(s) using it. Most containers that would normally connect to a mounted docker.sock can have their endpoint overridden using the DOCKER_HOST environment variable if they do not offer the option in their configuration; it should typically be pointed to tcp://socket-proxy:2375.

>Never expose this **container's port to a public network**. It should be treated the same way you would treat the docker socket or TCP endpoint.

### Suggested Resolution
Given that this is likely to be used as part of a SWAG setup, I suggest clarifying which (if either) of the following is true:

1. Both the SWAG containers and the docker-socket-proxy containers should be run on `network: lsio`. You set the DOCKER_HOST environment variable to tcp://socket-proxy:2375 and as long as you don't expose 2375 in any container you are ok.

2. The SWAG and public-facing containers should be on `network: lsio` and the docker-socket-proxy should, as indicated in the current compose, not have any network attachment.

In any event, it would be fantastic to have this be the default for the SWAG setup given that it's at least a little more secure (or at least show show the DSP within the context of a SWAG setup).

**Comment by thespad** [comment]
We don't provide named networks in our compose/run examples because we have no way of knowing what networks people and using and it would break for all the people who blindly copy/paste.

Your first example is the correct option; or more accurately *a* correct option, as there are other configurations that will also work.

The important part is not to publish port 2375 to the host on the socket proxy container, as it exposes your docker socket to the LAN (or worse, the public internet in the case of a poorly-configured VPS or AWS instance), and the docker socket does not provide an authentication layer (other than MTLS).

**Comment by Roxedus** [comment]
Swag doesnt need the socket by default. 

there is also the option of adding an additional network to swag with the socket proxy as the only other member.

**Comment by charles-lehman** [comment]
Thank you both, this is very helpful and now I think I get it.
